runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /(.+\.php)$
  script: \1

- url: /src/components/registerPage/register.php
  script: /src/components/registerPage/register.php